export const Chickens = {
  gold: {
    entity: 'oc:gold_chicken',
    block: ['minecraft:gold_block'],
    itemConvert: ['minecraft:gold_block'],
    entityToConvert: 'minecraft:chicken',
  },
  iron: {
    entity: 'oc:iron_chicken',
    block: ['minecraft:iron_block'],
    itemConvert: ['minecraft:iron_block'],
    entityToConvert: 'minecraft:chicken',
  },
  coal: {
    entity: 'oc:coal_chicken',
    block: ['minecraft:coal_block'],
    itemConvert: ['minecraft:coal_block'],
    entityToConvert: 'minecraft:chicken',
  },
  lapis: {
    entity: 'oc:lapis_chicken',
    block: ['minecraft:lapis_block'],
    itemConvert: ['minecraft:lapis_block'],
    entityToConvert: 'minecraft:chicken',
  },
  amethyst: {
    entity: 'oc:amethyst_chicken',
    block: ['minecraft:amethyst_block'],
    itemConvert: ['minecraft:budding_amethyst'],
    entityToConvert: 'minecraft:chicken',
  },
  redstone: {
    entity: 'oc:redstone_chicken',
    block: ['minecraft:redstone_block'],
    itemConvert: ['minecraft:redstone_block'],
    entityToConvert: 'minecraft:chicken',
  },
  copper: {
    entity: 'oc:copper_chicken',
    block: [
      'minecraft:copper_block',
      'minecraft:exposed_copper',
      'minecraft:weathered_copper',
      'minecraft:oxidized_copper',
      'minecraft:waxed_copper',
      'minecraft:waxed_exposed_copper',
      'minecraft:waxed_weathered_copper',
      'minecraft:waxed_oxidized_copper',
      'minecraft:cut_copper',
      'minecraft:exposed_cut_copper',
      'minecraft:weathered_cut_copper',
      'minecraft:oxidized_cut_copper',
      'minecraft:waxed_cut_copper',
      'minecraft:waxed_exposed_cut_copper',
      'minecraft:waxed_weathered_cut_copper',
      'minecraft:waxed_oxidized_cut_copper',
      'minecraft:chiseled_copper',
      'minecraft:exposed_chiseled_copper',
      'minecraft:weathered_chiseled_copper',
      'minecraft:oxidized_chiseled_copper',
      'minecraft:waxed_chiseled_copper',
      'minecraft:waxed_exposed_chiseled_copper',
      'minecraft:waxed_weathered_chiseled_copper',
      'minecraft:waxed_oxidized_chiseled_copper',
    ],
    itemConvert: [
      'minecraft:copper_block',
      'minecraft:exposed_copper',
      'minecraft:weathered_copper',
      'minecraft:oxidized_copper',
      'minecraft:waxed_copper',
      'minecraft:waxed_exposed_copper',
      'minecraft:waxed_weathered_copper',
      'minecraft:waxed_oxidized_copper',
      'minecraft:cut_copper',
      'minecraft:exposed_cut_copper',
      'minecraft:weathered_cut_copper',
      'minecraft:oxidized_cut_copper',
      'minecraft:waxed_cut_copper',
      'minecraft:waxed_exposed_cut_copper',
      'minecraft:waxed_weathered_cut_copper',
      'minecraft:waxed_oxidized_cut_copper',
      'minecraft:chiseled_copper',
      'minecraft:exposed_chiseled_copper',
      'minecraft:weathered_chiseled_copper',
      'minecraft:oxidized_chiseled_copper',
      'minecraft:waxed_chiseled_copper',
      'minecraft:waxed_exposed_chiseled_copper',
      'minecraft:waxed_weathered_chiseled_copper',
      'minecraft:waxed_oxidized_chiseled_copper',
    ],
    entityToConvert: 'minecraft:chicken',
  },
  diamond: {
    entity: 'oc:diamond_chicken',
    block: ['minecraft:diamond_block'],
    itemConvert: ['minecraft:diamond_block'],
    entityToConvert: 'minecraft:chicken',
  },
  emerald: {
    entity: 'oc:emerald_chicken',
    block: ['minecraft:emerald_block'],
    itemConvert: ['minecraft:emerald_block'],
    entityToConvert: 'minecraft:chicken',
  },
  quartz: {
    entity: 'oc:quartz_chicken',
    block: ['minecraft:quartz_block'],
    itemConvert: [
      'minecraft:quartz_block',
      'minecraft:quartz_bricks',
      'minecraft:quartz_pillar',
      'minecraft:chiseled_quartz_block',
      'minecraft:smooth_quartz',
    ],
    entityToConvert: 'minecraft:chicken',
  },
  netherite: {
    entity: 'oc:netherite_chicken',
    block: ['minecraft:netherite_block'],
    itemConvert: ['minecraft:netherite_upgrade_smithing_template'],
    entityToConvert: 'oc:diamond_chicken',
    sound: 'smithing_table.use',
  },
};
